package model;

// Generated 28 avr. 2015 00:46:40 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

import org.hibernate.annotations.Proxy;

/**
 * Agent generated by hbm2java
 */
@Entity
@Table(name = "agent", catalog = "ibm_pfe")
@XmlRootElement
@Proxy(lazy=false)
public class Agent implements java.io.Serializable {

	private int idAgent;
	private Role role;
	private String nom;
	private String prenom;
	private String adresse;
	private String numMobile;
	private String username;
	private String password;
	private Set<CreditImmobilier> creditImmobiliers = new HashSet<CreditImmobilier>(
			0);
	private Set<Notification> notifications = new HashSet<Notification>(0);

	public Agent() {
	}

	public Agent(int idAgent) {
		this.idAgent = idAgent;
	}

	public Agent(int idAgent, Role role, String nom, String prenom,
			String adresse, String numMobile, String username, String password,
			Set<CreditImmobilier> creditImmobiliers,
			Set<Notification> notifications) {
		this.idAgent = idAgent;
		this.role = role;
		this.nom = nom;
		this.prenom = prenom;
		this.adresse = adresse;
		this.numMobile = numMobile;
		this.username = username;
		this.password = password;
		this.creditImmobiliers = creditImmobiliers;
		this.notifications = notifications;
	}

	@Id
	@Column(name = "id_agent", unique = true, nullable = false)
	public int getIdAgent() {
		return this.idAgent;
	}

	public void setIdAgent(int idAgent) {
		this.idAgent = idAgent;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_role")
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@Column(name = "nom", length = 254)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", length = 254)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "adresse", length = 254)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "num_mobile", length = 254)
	public String getNumMobile() {
		return this.numMobile;
	}

	public void setNumMobile(String numMobile) {
		this.numMobile = numMobile;
	}

	@Column(name = "username", length = 254)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", length = 254)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "agent")
	public Set<CreditImmobilier> getCreditImmobiliers() {
		return this.creditImmobiliers;
	}

	public void setCreditImmobiliers(Set<CreditImmobilier> creditImmobiliers) {
		this.creditImmobiliers = creditImmobiliers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "agent")
	public Set<Notification> getNotifications() {
		return this.notifications;
	}

	public void setNotifications(Set<Notification> notifications) {
		this.notifications = notifications;
	}

}
