package model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

// Generated 17 avr. 2015 13:33:09 by Hibernate Tools 4.0.0


/**
 * Client generated by hbm2java
 */
@Entity
@Table(name = "client", catalog = "ibm")
@XmlRootElement

public class Client implements java.io.Serializable {

	private int id;
	private String firstName;
	private String lastName;
	private String nationality;
	private String email;
	private String adresse;
	private String ville;
	private String mobile;
	private String monthlyIncome;
	private boolean personalLoans;
	private String mpPersonalLoans;
	private boolean carLoans;
	private String mpCarLoans;
	private boolean existingMortgages;
	private String mpExistingMortgages;
	private boolean existingDebitCard;
	private boolean existingCreditCard;
	private int dob;

	
	
	public Client() {
	}

	public Client(int id, String firstName, String lastName,
			String nationality) {
		this.id = id;
		this.firstName = firstName;
		this.lastName = lastName;
		this.nationality = nationality;
		
	  }
	public Client(int id, String firstName, String lastName,
			String nationality, String email, String adresse, String ville,
			String mobile, String monthlyIncome, boolean personalLoans,
			String mpPersonalLoans, boolean carLoans, String mpCarLoans,
			boolean existingMortgages, String mpExistingMortgages,
			boolean existingDebitCard, boolean existingCreditCard, int dob) {
		this.id = id;
		this.firstName = firstName;
		this.lastName = lastName;
		this.nationality = nationality;
		this.email = email;
		this.adresse = adresse;
		this.ville = ville;
		this.mobile = mobile;
		this.monthlyIncome = monthlyIncome;
		this.personalLoans = personalLoans;
		this.mpPersonalLoans = mpPersonalLoans;
		this.carLoans = carLoans;
		this.mpCarLoans = mpCarLoans;
		this.existingMortgages = existingMortgages;
		this.mpExistingMortgages = mpExistingMortgages;
		this.existingDebitCard = existingDebitCard;
		this.existingCreditCard = existingCreditCard;
		this.dob = dob;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@XmlTransient
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "First_name", nullable = false, length = 40)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "Last_name", nullable = false, length = 40)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "Nationality", nullable = false, length = 40)
	public String getNationality() {
		return this.nationality;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

	@Column(name = "Email", nullable = true, length = 40)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "adresse", nullable = true, length = 40)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "ville", nullable = true, length = 40)
	public String getVille() {
		return this.ville;
	}

	public void setVille(String ville) {
		this.ville = ville;
	}

	@Column(name = "Mobile", nullable = true, length = 40)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "Monthly_income", nullable = true, length = 40)
	public String getMonthlyIncome() {
		return this.monthlyIncome;
	}

	public void setMonthlyIncome(String monthlyIncome) {
		this.monthlyIncome = monthlyIncome;
	}

	@Column(name = "personal_loans", nullable = true)
	public boolean isPersonalLoans() {
		return this.personalLoans;
	}

	public void setPersonalLoans(boolean personalLoans) {
		this.personalLoans = personalLoans;
	}

	@Column(name = "MP_personal_loans", nullable = true, length = 40)
	public String getMpPersonalLoans() {
		return this.mpPersonalLoans;
	}

	public void setMpPersonalLoans(String mpPersonalLoans) {
		this.mpPersonalLoans = mpPersonalLoans;
	}

	@Column(name = "car_loans", nullable = true)
	public boolean isCarLoans() {
		return this.carLoans;
	}

	public void setCarLoans(boolean carLoans) {
		this.carLoans = carLoans;
	}

	@Column(name = "MP_car_loans", nullable = true, length = 40)
	public String getMpCarLoans() {
		return this.mpCarLoans;
	}

	public void setMpCarLoans(String mpCarLoans) {
		this.mpCarLoans = mpCarLoans;
	}

	@Column(name = "existing_mortgages", nullable = true)
	public boolean isExistingMortgages() {
		return this.existingMortgages;
	}

	public void setExistingMortgages(boolean existingMortgages) {
		this.existingMortgages = existingMortgages;
	}

	@Column(name = "MP_existing_mortgages", nullable = true, length = 40)
	public String getMpExistingMortgages() {
		return this.mpExistingMortgages;
	}

	public void setMpExistingMortgages(String mpExistingMortgages) {
		this.mpExistingMortgages = mpExistingMortgages;
	}

	@Column(name = "Existing_debit_card", nullable = true)
	public boolean isExistingDebitCard() {
		return this.existingDebitCard;
	}

	public void setExistingDebitCard(boolean existingDebitCard) {
		this.existingDebitCard = existingDebitCard;
	}

	@Column(name = "Existing_credit_card", nullable = true)
	public boolean isExistingCreditCard() {
		return this.existingCreditCard;
	}

	public void setExistingCreditCard(boolean existingCreditCard) {
		this.existingCreditCard = existingCreditCard;
	}

	@Column(name = "dob", nullable = true)
	public int getDob() {
		return this.dob;
	}

	public void setDob(int dob) {
		this.dob = dob;
	}

}
