package model;

// Generated 28 avr. 2015 00:46:40 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

import org.hibernate.annotations.Proxy;

/**
 * CreditImmobilier generated by hbm2java
 */
@Entity
@Table(name = "credit_immobilier", catalog = "ibm_pfe")
@XmlRootElement
public class CreditImmobilier implements java.io.Serializable {

	private int idCredit;
	private TypeImmeuble typeImmeuble;
	private Existence existence;
	private TypeResidence typeRedisence;
	private Agent agent;
	private Clients clients;
	private Float tauxInteret;
	private Float montantPret;
	private Date dateOrigine;
	private Date echance;
	private Float mensualite;
	private String residencePrimaire;
	private Float surfaceTerre;
	private Integer surfaceConstruction;
	private String entrepreneurConstruction;
	private Float estimationConstruction;
	private Float estimationPropriete;
	private byte[] documentRegistration;

	public CreditImmobilier() {
	}

	public CreditImmobilier(int idCredit, Existence existence, Agent agent,
			Clients clients) {
		this.idCredit = idCredit;
		this.existence = existence;
		this.agent = agent;
		this.clients = clients;
	}

	public CreditImmobilier(int idCredit, TypeImmeuble typeImmeuble,
			Existence existence, TypeResidence typeRedisence, Agent agent,
			Clients clients, Float tauxInteret, Float montantPret,
			Date dateOrigine, Date echance, Float mensualite,
			String residencePrimaire, Float surfaceTerre,
			Integer surfaceConstruction, String entrepreneurConstruction,
			Float estimationConstruction, Float estimationPropriete,
			byte[] documentRegistration) {
		this.idCredit = idCredit;
		this.typeImmeuble = typeImmeuble;
		this.existence = existence;
		this.typeRedisence = typeRedisence;
		this.agent = agent;
		this.clients = clients;
		this.tauxInteret = tauxInteret;
		this.montantPret = montantPret;
		this.dateOrigine = dateOrigine;
		this.echance = echance;
		this.mensualite = mensualite;
		this.residencePrimaire = residencePrimaire;
		this.surfaceTerre = surfaceTerre;
		this.surfaceConstruction = surfaceConstruction;
		this.entrepreneurConstruction = entrepreneurConstruction;
		this.estimationConstruction = estimationConstruction;
		this.estimationPropriete = estimationPropriete;
		this.documentRegistration = documentRegistration;
	}

	@Id
	@Column(name = "id_credit", unique = true, nullable = false)
	public int getIdCredit() {
		return this.idCredit;
	}

	public void setIdCredit(int idCredit) {
		this.idCredit = idCredit;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_type")
	public TypeImmeuble getTypeImmeuble() {
		return this.typeImmeuble;
	}

	public void setTypeImmeuble(TypeImmeuble typeImmeuble) {
		this.typeImmeuble = typeImmeuble;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_existence", nullable = false)
	public Existence getExistence() {
		return this.existence;
	}

	public void setExistence(Existence existence) {
		this.existence = existence;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_residence")
	public TypeResidence getTypeRedisence() {
		return this.typeRedisence;
	}

	public void setTypeRedisence(TypeResidence typeRedisence) {
		this.typeRedisence = typeRedisence;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_agent", nullable = false)
	public Agent getAgent() {
		return this.agent;
	}

	public void setAgent(Agent agent) {
		this.agent = agent;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_client", nullable = false)
	public Clients getClients() {
		return this.clients;
	}

	public void setClients(Clients clients) {
		this.clients = clients;
	}

	@Column(name = "taux_interet", precision = 12, scale = 0)
	public Float getTauxInteret() {
		return this.tauxInteret;
	}

	public void setTauxInteret(Float tauxInteret) {
		this.tauxInteret = tauxInteret;
	}

	@Column(name = "montant_pret", precision = 12, scale = 0)
	public Float getMontantPret() {
		return this.montantPret;
	}

	public void setMontantPret(Float montantPret) {
		this.montantPret = montantPret;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_origine", length = 19)
	public Date getDateOrigine() {
		return this.dateOrigine;
	}

	public void setDateOrigine(Date dateOrigine) {
		this.dateOrigine = dateOrigine;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "echance", length = 19)
	public Date getEchance() {
		return this.echance;
	}

	public void setEchance(Date echance) {
		this.echance = echance;
	}

	@Column(name = "mensualite", precision = 12, scale = 0)
	public Float getMensualite() {
		return this.mensualite;
	}

	public void setMensualite(Float mensualite) {
		this.mensualite = mensualite;
	}

	@Column(name = "residence_primaire", length = 30)
	public String getResidencePrimaire() {
		return this.residencePrimaire;
	}

	public void setResidencePrimaire(String residencePrimaire) {
		this.residencePrimaire = residencePrimaire;
	}

	@Column(name = "surface_terre", precision = 12, scale = 0)
	public Float getSurfaceTerre() {
		return this.surfaceTerre;
	}

	public void setSurfaceTerre(Float surfaceTerre) {
		this.surfaceTerre = surfaceTerre;
	}

	@Column(name = "surface_construction")
	public Integer getSurfaceConstruction() {
		return this.surfaceConstruction;
	}

	public void setSurfaceConstruction(Integer surfaceConstruction) {
		this.surfaceConstruction = surfaceConstruction;
	}

	@Column(name = "entrepreneur_construction", length = 30)
	public String getEntrepreneurConstruction() {
		return this.entrepreneurConstruction;
	}

	public void setEntrepreneurConstruction(String entrepreneurConstruction) {
		this.entrepreneurConstruction = entrepreneurConstruction;
	}

	@Column(name = "estimation_construction", precision = 12, scale = 0)
	public Float getEstimationConstruction() {
		return this.estimationConstruction;
	}

	public void setEstimationConstruction(Float estimationConstruction) {
		this.estimationConstruction = estimationConstruction;
	}

	@Column(name = "estimation_propriete", precision = 12, scale = 0)
	public Float getEstimationPropriete() {
		return this.estimationPropriete;
	}

	public void setEstimationPropriete(Float estimationPropriete) {
		this.estimationPropriete = estimationPropriete;
	}

	@Column(name = "document_registration")
	public byte[] getDocumentRegistration() {
		return this.documentRegistration;
	}

	public void setDocumentRegistration(byte[] documentRegistration) {
		this.documentRegistration = documentRegistration;
	}

}
