package model;

// Generated 28 avr. 2015 00:46:40 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

import org.hibernate.annotations.Proxy;

/**
 * DirectionBq generated by hbm2java
 */
@Entity
@Table(name = "direction_bq", catalog = "ibm_pfe")
@XmlRootElement

public class DirectionBq implements java.io.Serializable {

	private int idDirection;
	private String equipe;
	private Set<Expert> experts = new HashSet<Expert>(0);

	public DirectionBq() {
	}

	public DirectionBq(int idDirection) {
		this.idDirection = idDirection;
	}

	public DirectionBq(int idDirection, String equipe, Set<Expert> experts) {
		this.idDirection = idDirection;
		this.equipe = equipe;
		this.experts = experts;
	}

	@Id
	@Column(name = "id_direction", unique = true, nullable = false)
	public int getIdDirection() {
		return this.idDirection;
	}

	public void setIdDirection(int idDirection) {
		this.idDirection = idDirection;
	}

	@Column(name = "equipe", length = 40)
	public String getEquipe() {
		return this.equipe;
	}

	public void setEquipe(String equipe) {
		this.equipe = equipe;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "directionBq")
	public Set<Expert> getExperts() {
		return this.experts;
	}

	public void setExperts(Set<Expert> experts) {
		this.experts = experts;
	}

}
