package model;

// Generated 28 avr. 2015 00:46:40 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Proxy;

/**
 * Langue generated by hbm2java
 */
@Entity
@Table(name = "langue", catalog = "ibm_pfe")
public class Langue implements java.io.Serializable {

	private int idLangue;
	private String nom;
	private Set<Clients> clientses = new HashSet<Clients>(0);

	public Langue() {
	}

	public Langue(int idLangue) {
		this.idLangue = idLangue;
	}

	public Langue(int idLangue, String nom, Set<Clients> clientses) {
		this.idLangue = idLangue;
		this.nom = nom;
		this.clientses = clientses;
	}

	@Id
	@Column(name = "id_langue", unique = true, nullable = false)
	public int getIdLangue() {
		return this.idLangue;
	}

	public void setIdLangue(int idLangue) {
		this.idLangue = idLangue;
	}

	@Column(name = "nom", length = 254)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "langue")
	public Set<Clients> getClientses() {
		return this.clientses;
	}

	public void setClientses(Set<Clients> clientses) {
		this.clientses = clientses;
	}

}
