package model;

// Generated 28 avr. 2015 00:46:40 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

import org.hibernate.annotations.Proxy;

/**
 * Notification generated by hbm2java
 */
@Entity
@Table(name = "notification", catalog = "ibm_pfe")
@XmlRootElement

public class Notification implements java.io.Serializable {

	private int idNotification;
	private Expert expert;
	private Agent agent;
	private String reponse;
	private String statut;

	public Notification() {
	}

	public Notification(int idNotification) {
		this.idNotification = idNotification;
	}

	public Notification(int idNotification, Expert expert, Agent agent,
			String reponse, String statut) {
		this.idNotification = idNotification;
		this.expert = expert;
		this.agent = agent;
		this.reponse = reponse;
		this.statut = statut;
	}

	@Id
	@Column(name = "id_notification", unique = true, nullable = false)
	public int getIdNotification() {
		return this.idNotification;
	}

	public void setIdNotification(int idNotification) {
		this.idNotification = idNotification;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_expert")
	public Expert getExpert() {
		return this.expert;
	}

	public void setExpert(Expert expert) {
		this.expert = expert;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_agent")
	public Agent getAgent() {
		return this.agent;
	}

	public void setAgent(Agent agent) {
		this.agent = agent;
	}

	@Column(name = "reponse", length = 100)
	public String getReponse() {
		return this.reponse;
	}

	public void setReponse(String reponse) {
		this.reponse = reponse;
	}

	@Column(name = "statut", length = 100)
	public String getStatut() {
		return this.statut;
	}

	public void setStatut(String statut) {
		this.statut = statut;
	}

}
