package model;

// Generated 28 avr. 2015 00:46:40 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSeeAlso;

import org.hibernate.annotations.Proxy;


/**
 * Ville generated by hbm2java
 */
@Entity
@Table(name = "ville", catalog = "ibm_pfe")
@XmlRootElement



public class Ville implements java.io.Serializable {

	private int idVille;
	private Pays pays;
	private String name;
	private Set<Clients> clientses = new HashSet<Clients>(0);

	public Ville() {
	}

	public Ville(int idVille) {
		this.idVille = idVille;
	}

	public Ville(int idVille, Pays pays, String name, Set<Clients> clientses) {
		this.idVille = idVille;
		this.pays = pays;
		this.name = name;
		this.clientses = clientses;
	}

	@Id
	@Column(name = "id_ville", unique = true, nullable = false)
	public int getIdVille() {
		return this.idVille;
	}

	public void setIdVille(int idVille) {
		this.idVille = idVille;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_pays")
	public Pays getPays() {
		return this.pays;
	}

	public void setPays(Pays pays) {
		this.pays = pays;
	}

	@Column(name = "name", length = 254)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ville")
	public Set<Clients> getClientses() {
		return this.clientses;
	}

	public void setClientses(Set<Clients> clientses) {
		this.clientses = clientses;
	}

}
